//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanoleafAuroraSdk.Test.SampleResponses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleResponseBodies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleResponseBodies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NanoleafAuroraSdk.Test.SampleResponses.SampleResponseBodies", typeof(SampleResponseBodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  &quot;Be Productive&quot;,
        ///  &quot;Be Zen&quot;,
        ///  &quot;Candy Grams&quot;,
        ///  &quot;Cherry blossom&quot;,
        ///  &quot;Color Burst&quot;,
        ///  &quot;Fireworks and Firecrackers&quot;,
        ///  &quot;Flames&quot;,
        ///  &quot;Floating Balloons&quot;,
        ///  &quot;Forest&quot;,
        ///  &quot;Forest Sunrise&quot;,
        ///  &quot;Forest XYZ&quot;,
        ///  &quot;Green Snake&quot;,
        ///  &quot;Inner Peace&quot;,
        ///  &quot;Lonely&quot;,
        ///  &quot;Lounge&quot;,
        ///  &quot;Natural Light&quot;,
        ///  &quot;Nemo&quot;,
        ///  &quot;Northern Lights&quot;,
        ///  &quot;Rainy Light&quot;,
        ///  &quot;Romantic&quot;,
        ///  &quot;Roses Are Red&quot;,
        ///  &quot;Sky Mode&quot;,
        ///  &quot;Snow Day&quot;,
        ///  &quot;Snow flurry&quot;,
        ///  &quot;Snowfall&quot;,
        ///  &quot;Sunlight through trees&quot;,
        ///  &quot;Tropical Waterfall&quot;,
        ///  &quot;Vineyard V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EffectsListResponse {
            get {
                return ResourceManager.GetString("EffectsListResponse", resourceCulture);
            }
        }
    }
}
